---
title: "Using D3 w/ R Markdown"
author: "Eric Bickel"
date: 2017-05-09
categories: ["R"]
tags: ["rmarkdown", "d3.js", "visualization"]
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)

## Load packages

# Data loading
library(jsonlite)
library(tidyjson)

# Data manipulation
library(tidyverse)

# Data visualization
library(ggthemes)
library(extrafont)
library(scales)

```

```{r, pull-data, include = FALSE}

## Read in json file
network.data <- jsonlite::fromJSON(txt = '../../../blogdown_source/data/user_networks.json', 
                         simplifyDataFrame = TRUE)

# Remove '@' from reviewer names 
network.data$author <- gsub('@', '', network.data$author)

# Replace character(0) comment-author elements
network.data <- network.data %>% 
  mutate(comment_authors = map2(author, `comment-authors`, function(a, ca) { ifelse(nrow(data.frame(ca)) == 0, a, return(ca) )}))

## Replicate author names based on the number of commenters

# Find the number of commenters
network.data <- network.data %>% 
  mutate(n_comment_authors = map_dbl(`comment_authors`, function(i) length(i)))

# Remove reviews with less than 5 comments
network.data <- network.data[network.data$n_comment_authors > 5, ]

# Number of reviews by individual
n_reviews <- data.frame(table(network.data$author))

# Replicate review data based on the number of commenters
network.data_expanded <- data.frame('review_author' = rep(network.data$author, network.data$n_comment_authors), 
                           'comment_author' = unlist(network.data$comment_authors),
                           'product' = rep(network.data$product, network.data$n_comment_authors),
                           'brand' = rep(network.data$brand, network.data$n_comment_authors),
                           'type' = rep(network.data$type, network.data$n_comment_authors))

# Remove '@' from commenter names
network.data_expanded$comment_author <- gsub('@', '', network.data_expanded$comment_author)

# Number of comments
n_comments <- data.frame(table(network.data_expanded$comment_author))
names(n_comments) <- c('Var1', 'comments')

# Build column of review and comment authors
authors_total <- rbind(data.frame('auth' = network.data_expanded$review_author),
                       data.frame('auth' = network.data_expanded$comment_author))

authors_total <- data.frame('auth' = unique(gsub('@', '', authors_total$auth)))

# Build node data
nodes <- data.frame('id' = paste0('c', seq(from = 1, to = nrow(authors_total))),
                    'name' = authors_total,
                    'n_reviews' = left_join(left_join(authors_total, 
                                            n_reviews,
                                            by = c('auth' = 'Var1')),
                                            n_comments,
                                            by = c('auth' = 'Var1'))) %>% 
  select(-n_reviews.auth) %>%
  mutate(t_interactions = ifelse(is.na(n_reviews.Freq), 0, n_reviews.Freq) + ifelse(is.na(n_reviews.comments), 0, n_reviews.comments)) %>% 
  select(-n_reviews.Freq, -n_reviews.comments)

# Build edge data
edges <- data.frame('from' = left_join(network.data_expanded,
                                       nodes,
                                       by = c('review_author' = 'auth')),
                    'to' = left_join(network.data_expanded,
                                     nodes,
                                     by = c('comment_author' = 'auth'))) %>% 
  select(from.id, to.id) %>% 
  distinct(from.id, to.id)

## Find most active users and networks

# Remove reviews with less than 5 comments
network.data_active <- network.data[network.data$n_comment_authors > 20, ]

# Number of reviews by individual
n_reviews_active <- data.frame(table(network.data_active$author))

# Replicate review data based on the number of commenters
network.data_active_expanded <- data.frame('review_author' = rep(network.data_active$author, network.data_active$n_comment_authors), 
                           'comment_author' = unlist(network.data_active$comment_authors),
                           'product' = rep(network.data_active$product, network.data_active$n_comment_authors),
                           'brand' = rep(network.data_active$brand, network.data_active$n_comment_authors),
                           'type' = rep(network.data_active$type, network.data_active$n_comment_authors))

# Remove '@' from commenter names
network.data_active_expanded$comment_author <- gsub('@', '', network.data_active_expanded$comment_author)

# Number of comments
n_comments_active <- data.frame(table(network.data_active_expanded$comment_author))
names(n_comments_active) <- c('Var1', 'comments')

# Build column of review and comment authors
authors_total_expanded <- rbind(data.frame('auth' = network.data_expanded$review_author),
                       data.frame('auth' = network.data_expanded$comment_author))

authors_total_expanded <- data.frame('auth' = unique(gsub('@', '', authors_total_expanded$auth)))

authors_total_active <- data.frame('auth' = authors_total_expanded[authors_total_expanded$auth %in% n_reviews_active$Var1 | 
                                                            authors_total_expanded$auth %in% n_comments_active$Var1, ])

# Build node data
nodes_expanded <- data.frame('id' = paste0('c', seq(from = 1, to = nrow(authors_total_active))),
                    'name' = authors_total_active,
                    'n_reviews' = left_join(left_join(authors_total_active, 
                                            n_reviews,
                                            by = c('auth' = 'Var1')),
                                            n_comments,
                                            by = c('auth' = 'Var1'))) %>% 
  select(-n_reviews.auth) %>%
  mutate(t_interactions = ifelse(is.na(n_reviews.Freq), 0, n_reviews.Freq) + ifelse(is.na(n_reviews.comments), 0, n_reviews.comments)) %>% 
  select(-n_reviews.Freq, -n_reviews.comments)

# Build edge data
edges_expanded <- data.frame('from' = left_join(network.data_expanded,
                                       nodes_expanded,
                                       by = c('review_author' = 'auth')),
                    'to' = left_join(network.data_expanded,
                                     nodes_expanded,
                                     by = c('comment_author' = 'auth'))) %>% 
  select(from.id, to.id) %>% 
  distinct(from.id, to.id)

# Remove na rows
edges_expanded <- na.omit(edges_expanded)

# Add source and target author names
edges_expanded <- edges_expanded %>% 
  mutate('source' = left_join(edges_expanded,
                                 nodes_expanded,
                                 by = c('from.id' = 'id'))$auth,
         'target' = left_join(edges_expanded,
                                 nodes_expanded,
                                 by = c('to.id' = 'id'))$auth)

# write_csv(edges_expanded, 'links_active.csv')

```

```{r vectors-to-json, include = FALSE, echo=FALSE, results="asis"}
cat(
  paste(
  '<script>
    var links = ',toJSON(edges_expanded),';
  </script>'
  , sep="")
)
```

<div id="plot"></div>

<script src="https://d3js.org/d3.v3.min.js"></script>

```{js, include = FALSE}
// <script>

var width = 950,
    height = 700;

var svg = d3.select("#plot").append("svg")
    .attr("width", width)
    .attr("height", height);

var tooltip = d3.select("#plot")
  .append("div")
  .attr("class", "my-tooltip") //add the tooltip class
  .style("position", "absolute")
  .style("z-index", "10")
  .style("visibility", "hidden");

var force = d3.layout.force()
    .size([width, height]);

var nodesByName = {};

// Create nodes for each unique source and target.
links.forEach(function(link) {
  link.source = nodeByName(link.source);
  link.target = nodeByName(link.target);
});

// Extract the array of nodes from the map by name.
var nodes = d3.values(nodesByName);

// Create the link lines.
var link = svg.selectAll(".link")
    .data(links)
  .enter().append("line")
    .attr("class", "link");

// Create circles for each user
var circle = svg.append("g").selectAll("circle")
  .data(nodes)
.enter().append("circle")
  .attr("r", 6)
  .call(force.drag)
  .on("mousemove", function() {
    return tooltip.style("top", (d3.event.pageY - 40) + "px").style("left", (d3.event.pageX - 130) + "px");
  })
  .on("mouseout", function() {
    return tooltip.style("visibility", "hidden");
  })
  .on('mouseover', function(d) {
    console.log(d.name);
    tooltip.style("visibility", "visible")
      .text(d.name)
    link.style('stroke-width', function(l) {
      if (d === l.source || d === l.target)
          return 2;
      else
          return 0;
  });
    link.style('stroke', function(l) {
      if (d === l.source || d === l.target)
          return "#008abc";
      else
          return "#f0f2f3";
  });
});

// Start the force layout.
force
        .nodes(nodes)
        .links(links)
        .linkDistance(400)
        .charge(1)
        // .gravity(1)
        .on("tick", tick)
        .start();

// Define tick function to move the nodes around
function tick() {
  link.attr("x1", function(d) { return d.source.x; })
      .attr("y1", function(d) { return d.source.y; })
      .attr("x2", function(d) { return d.target.x; })
      .attr("y2", function(d) { return d.target.y; });

  circle.attr("cx", function(d) { return d.x = Math.max(15, Math.min(width - 15, d.x)); })
      .attr("cy", function(d) { return d.y= Math.max(15, Math.min(height - 15, d.y)); });
    }

function nodeByName(name) {
  return nodesByName[name] || (nodesByName[name] = {name: name});
}

function transform(d) {
  return "translate(" + d.x + "," + d.y + ")";
}

// </script>

```